# It is necessary to enable the Service Networking API
# to use Private IPs with CloudSQL
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: servicenetworking.googleapis.com
  namespace: trifacta-infrastructure